name: action1
on: [push]
jobs:
  KochbuchBauen:
    runs-on: ubuntu-latest
    steps:
      # gets the latest repo
      - uses: actions/checkout@v3
      - name: Erstmal sehen, dann mal schaun
        run: bash makefile.sh
      