name: action1
on: [push]
jobs:
  KochbuchBauen:
    runs-on: ubuntu-latest
    steps:
      # asciidoktor installieren
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-add-repository -y ppa:rael-gc/rvm
      - run: sudo apt-get update
      - run: sudo apt-get install rvm
      - run: sudo usermod -a -G rvm $USER
      - run: rvm install ruby
      - run: sudo apt-get install asciidoctor
      - run: gem install asciidoctor-pdf
      # gets the latest repo
      - uses: actions/checkout@v3
      - name: Erstmal sehen, dann mal schaun
        run: bash makefile.sh
      