name: action1
on: [push]
jobs:
  ersterversuch:
    runs-on: ubuntu-latest
    steps:
      - name: Erstmal sehen, dann mal schaun
        run: echo "Hello world!"
              pwd
              ls -altr